package com.pixel.hc2nerf;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;
import com.mojang.brigadier.Command;
import com.mojang.brigadier.arguments.StringArgumentType;
import com.mojang.brigadier.context.CommandContext;
import com.mojang.brigadier.suggestion.Suggestions;
import com.mojang.brigadier.suggestion.SuggestionsBuilder;
import com.mojang.datafixers.util.Pair;
import com.mojang.logging.LogUtils;
import net.minecraft.commands.CommandSourceStack;
import net.minecraft.commands.Commands;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.network.chat.Component;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.food.FoodProperties;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraftforge.common.MinecraftForge;
import net.minecraftforge.event.RegisterCommandsEvent;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.fml.ModLoadingContext;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.config.ModConfig;
import net.minecraftforge.fml.event.lifecycle.FMLCommonSetupEvent;
import net.minecraftforge.fml.javafmlmod.FMLJavaModLoadingContext;
import net.minecraftforge.fml.loading.FMLEnvironment;
import net.minecraftforge.fml.util.ObfuscationReflectionHelper;
import net.minecraftforge.registries.ForgeRegistries;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.lang.reflect.Field;
import java.util.concurrent.CompletableFuture;

import org.slf4j.Logger;

// The value here should match an entry in the META-INF/mods.toml file
@Mod(HC2Nerf.MODID)
public class HC2Nerf
{
    // Define mod id in a common place for everything to reference
    public static final String MODID = "hc2nerf";
    // Directly reference a slf4j logger
    private static final Logger LOGGER = LogUtils.getLogger();

    public HC2Nerf()
    {
        IEventBus modEventBus = FMLJavaModLoadingContext.get().getModEventBus();

        // Register the commonSetup method for modloading
        modEventBus.addListener(this::commonSetup);

        // Register ourselves for server and other game events we are interested in
        MinecraftForge.EVENT_BUS.register(this);

        // Register our mod's ForgeConfigSpec so that Forge can create and load the config file for us
        ModLoadingContext.get().registerConfig(ModConfig.Type.COMMON, Config.SPEC);
    }

    private void commonSetup(final FMLCommonSetupEvent event)
    {
        LOGGER.info("nomnomnom :3");
        event.enqueueWork(() -> {
        JsonElement automaticData = loadFile("food-data/autogenerated.json");
        JsonElement manualData = loadFile("food-data/manual.json");
        JsonElement minecraftData = loadFile("food-data/minecraftnerf.json");
        JsonElement gbData = loadFile("food-data/gamebreaking.json");

        JsonArray itemsToChange = new JsonArray();
        // load arrays
        if (Config.nerfPams) {
            JsonObject aObj = automaticData.getAsJsonObject();
            JsonObject mObj = manualData.getAsJsonObject();
            JsonArray aitemsArray = aObj.getAsJsonArray("items");
            JsonArray mitemsArray = mObj.getAsJsonArray("items");
            itemsToChange = addArrays(itemsToChange, aitemsArray);
            itemsToChange = addArrays(itemsToChange, mitemsArray);
        }

        if (Config.nerfMinecraft) {
            JsonArray minecraftArray = minecraftData.getAsJsonObject().getAsJsonArray("items");
            itemsToChange = addArrays(itemsToChange, minecraftArray);
        }
        if (Config.nerfGamebreaking) {
            JsonArray gbArray = gbData.getAsJsonObject().getAsJsonArray("items");
            itemsToChange = addArrays(itemsToChange, gbArray);
        }
        if (itemsToChange.size() == 0) return;

        for (JsonElement jsonitem : itemsToChange) {
            JsonObject itemObj = jsonitem.getAsJsonObject();
            String id = itemObj.get("id").getAsString();
            int hunger = itemObj.get("hunger").getAsInt();
            float saturation = itemObj.get("saturation").getAsFloat();

            String[] split = id.split(":");
            Item i = ForgeRegistries.ITEMS.getValue(ResourceLocation.tryBuild(split[0], split[1]));
            if (i == null || i.toString().equals("minecraft:air"))
                continue; // in case some addon mods arent installed

            if (hunger == 0 && saturation == 0.0f) {
                    modifyItem(i, null);
                    continue;
            }

            ItemStack stack = new ItemStack(i);
            FoodProperties oldprops = stack.getFoodProperties(null);
            FoodProperties.Builder newprops = new FoodProperties.Builder().nutrition(hunger)
                    .saturationMod(saturation);
            if (oldprops != null) {
                for (Pair<MobEffectInstance, Float> e : oldprops.getEffects()) {
                    newprops.effect(() -> new MobEffectInstance(e.getFirst().getEffect(), e.getFirst().getDuration(), e.getFirst().getAmplifier(), e.getFirst().isAmbient(), e.getFirst().isVisible(), e.getFirst().showIcon()), e.getSecond());
                }
                if(oldprops.canAlwaysEat()) {
                    newprops.alwaysEat();
                }
                if (oldprops.isFastFood()) {
                    newprops.fast();
                }
            }
            modifyItem(i, newprops.build());
        }

    });


    }

    private void modifyItem(Item item, FoodProperties props) {
        try {
            Field foodfield = ObfuscationReflectionHelper.findField(Item.class, "f_41380_");
            foodfield.setAccessible(true);
            foodfield.set(item, props);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private JsonArray addArrays(JsonArray a, JsonArray b) {
        for (JsonElement e : b) {
            a.add(e);
        }
        return a;
    }

    private JsonElement loadFile(String fileName) {
        InputStream stream = getClass().getClassLoader().getResourceAsStream(fileName);
        InputStreamReader reader = new InputStreamReader(stream);
        if (stream == null) {
            LOGGER.error("Failed to find" + fileName);
        }
        JsonElement r = JsonParser.parseReader(reader);
        if (!r.isJsonObject()) {
            LOGGER.error(fileName + " could not be loaded! many food items will not be changed!!");
        }
        return r;
    }

    @SubscribeEvent
    public void registerCommands(RegisterCommandsEvent event) {
        if (FMLEnvironment.production)
            return;

        event.getDispatcher().register(
                Commands.literal("hc2nerf")
                        .then(Commands.argument("cmd", StringArgumentType.word())
                                .suggests((c, b) -> getSuggestions(b))
                                .executes(context -> {
                                    String cmd = StringArgumentType.getString(context, "cmd");
                                    if (cmd.equals("dumpItems")) {
                                        dumpItems(context);
                                    }
                                    return Command.SINGLE_SUCCESS;
                                })));
    }

    private static CompletableFuture<Suggestions> getSuggestions(SuggestionsBuilder builder) {
        builder.suggest("dumpItems");
        return builder.buildFuture();
    }

    private static void dumpItems(CommandContext<CommandSourceStack> context) {

        ServerPlayer p = context.getSource().getPlayer();
        if (p == null)
            return;

        p.sendSystemMessage(Component.literal("Preparing dump..."));
        try {
            BufferedWriter w = new BufferedWriter(new FileWriter("1.20.1_food.json"));
            w.write("");
            w.append("{\n");
            w.append(" \"items\": [\n");
            for (Item item : BuiltInRegistries.ITEM) {
                ItemStack stack = new ItemStack(item);
                FoodProperties food = item.getFoodProperties(stack, null);
                if (item.toString() == "apple") {
                    LOGGER.info("maou");
                }
                if (food != null) {
                    int foodamt = food.getNutrition();
                    float saturation = food.getSaturationModifier();
                    // LOGGER.info(item.toString() + foodamt + "-" + saturation);
                    String id = item.toString();
                    w.append(" " + "[\"" + id + "\", " + foodamt + ", " + saturation + "],\n");
                }
            }
            w.append(" ]\n");
            w.append("}");
            w.close();
            p.sendSystemMessage(Component.literal("Finished! :steamhappy:"));
        } catch (IOException e) {
            p.sendSystemMessage(Component.literal("Failed! " + e.getMessage()));
        }
    }
}
